### ISSUE TITLE
daemon process is exiting after receiving the first connection abruptly

### ISSUE THREAD

**Issue by kirantpatil** [mirasrael/daemons-rails#26]
If I run in the console with command (rake daemon:park) , I think the process run in foreground and does not exit but if I daemonize (rake daemon:park:start) it then it quits abruptly once it gets first connection request 

Here is my code below.

 # Replace this with your code
  s = UDPSocket.new
  s.bind("0.0.0.0", 2000)
  loop do
  text, sender = s.recvfrom(16)
  puts text
  s.send "aaa", 0, sender[3], sender[1]
  e = Event.find(1)
  e.pdata = text
  e.save
  end

**Comment by mirasrael** [comment]
Please, check logs. You can find error there.

**Comment by kirantpatil** [comment]
I am getting this error in log.

lib/daemons/park_ctl:6:in `<main>'
I, [2015-06-10T14:33:23.850758 #5947]  INFO -- : *** below you find all exception objects found in memory, some of them may have been thrown in your application, others may just be in memory because they are standard exceptions ***
E, [2015-06-10T14:33:23.851395 #5947] ERROR -- : stream closed (IOError)

E, [2015-06-10T14:33:23.851559 #5947] ERROR -- : failed to allocate memory (NoMemoryError)

E, [2015-06-10T14:33:23.851625 #5947] ERROR -- : stack level too deep (SystemStackError)

E, [2015-06-10T14:33:23.851812 #5947] ERROR -- : exception reentered (fatal)

E, [2015-06-10T14:33:23.865300 #5947] ERROR -- : Could not find table 'events' (ActiveRecord::StatementInvalid)
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:511:in `table_structure'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:385:in `columns'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/attributes.rb:93:in `columns'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/attributes.rb:98:in `columns_hash'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/activerecord-4.2.1/lib/active_record/core.rb:135:in `find'
/home/kpatil/work/nagaraj/svg_nload/lib/daemons/park.rb:26:in `block in <top (required)>'
/home/kpatil/work/nagaraj/svg_nload/lib/daemons/park.rb:22:in `loop'
/home/kpatil/work/nagaraj/svg_nload/lib/daemons/park.rb:22:in `<top (required)>'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/application.rb:218:in `load'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/application.rb:218:in `start_load'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/application.rb:297:in `start'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/controller.rb:56:in `run'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons.rb:144:in `block in run'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `call'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons/cmdline.rb:88:in `catch_exceptions'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-1.2.2/lib/daemons.rb:143:in `run'
/home/kpatil/.rvm/gems/ruby-2.2.2/gems/daemons-rails-1.2.1/lib/daemons/rail

**Comment by kirantpatil** [comment]
The above error is not hitting if I run as explained yesterday ie. run with command (rake daemon:park) where it listen in forground with out creating any daemon process.

**Comment by mirasrael** [comment]
I suspect it can use different environments for daemonized mode and for foreground mode. Can you check you settings for production and development mode databases? Are they both pointing to valid database?

**Comment by kirantpatil** [comment]
Yes, you nailed it.

It was pointing to production db and I pointed both dev and production mode to same db and it is no more exiting.

Thanks a lot..
