### ISSUE TITLE
If there is space in the directory, you can not reach

### ISSUE THREAD

**Issue by brunomacabeusbr** [mirasrael/daemons-rails#28]
In <a href="https://github.com/mirasrael/daemons-rails/blob/master/lib/daemons/rails/controller.rb">this file</a>, this line
`cd #{Daemons::Rails.configuration.root} && #{path} #{command} #{arguments unless argv.empty?}`

Needs to be replaced by
`cd "#{Daemons::Rails.configuration.root}" && "#{path}" #{command} #{arguments unless argv.empty?}`

**Comment by mirasrael** [comment]
Thanks for this. I added it. Feel free to open pull request next time ;)
