### ISSUE TITLE
New life for project (please join if you feed you may be useful)

### ISSUE THREAD

**Issue by bogdanRada** [mirasrael/daemons-rails#31]
Hello,
First of all i want to Say Thank You for this gem . I have been using it succesfully for a long time . 
I recently  saw You are looking for someone who can maintain the repository. I am interested in helping as much as i can. Let me know how can i help. 

I would also appreciate If You could give me some pointers maybe in the right direcțion..about what You might have planned to implement or something that maybe You already started and i could help with the implementation. 
     Let me know if You will accept my help

Thank You very much.

**Comment by mirasrael** [comment]
Hi @bogdanRada
First of all - thanks for your answer!
I'm mostly spoke about transfer of ownership, because I'm now not in Rails (or even Ruby) world. So if you ready to take ownership and keep this gem alive then you are welcome. Just let me know :) 

Otherwise if you just want to contribute and refresh this gem, then there are few most priority tasks on which you can work:

- Make this gem compatible with latest Rails versions (last supported version for now is 3 as far as I remember).
- Review and actualize issues

After that we can go in direction to new features ;)

**Comment by bogdanRada** [comment]
Hello, 
  Well i am ok about taking ownership though have to admit that i might not have a lot of time in the next 3-4 months maybe to work on this gem , due to some personal things that i need to handle. 
    But i really want to keep this gem alive, because i use it in my apps and works really nice with Rails 4.2.4 also, after some diggging through the "daemons" gem source code . There are some hidden tricks in there to make things work properly.  

    I am not totally sure what is the best approach for this.

   I  honestly think that maybe the best approach would be just to be added as a collaborator to the project 
and on rubygems.org also . This way you won't loose the ownership of the project  and i would have control over releases in case there is a need to release a new version and you might be unavailable .
 
    I prefer honestly the collaborator type over the ownership because this way my changes could still be reviewed by you . And this could be considered also as a trial period and later if you consider that i will be a potential good candidate based on how the work is done and the quality of the work....than we can discuss than about taking ownership if that is something that you might still want. 

 Or if you consider that you don't have the resources to still keep an eye on the project from time to time , i am ok with taking ownership of the project , though i feel like i should at least give others the opportunity at least to declare themselves also as potential candidates for taking ownership of the project. My point is that i don't want to steal others the opportunity of jumping in this discussion , because maybe some other guys could be better candidates with better skills than i have. 

Let me know what your decision is about the possibility to be a collaborator ( collaborators are different than contributors because they have full access to the repository, and will require access to rubygems.org also for this project) , or maybe just a contributor ( but than i will need approval for each action )  or  about taking ownership ( although like i said earlier i am not sure this is the right approach at this moment)  

Anyway i will try in the next days maybe to see what updates i can add to the project for compatiblity with other Rails versions  and  I will let you know as soon as i have something prepared. Hope i will have something soon. 

Have a nice day and thank you very much for taking the time to respond so quickly to this thread. 

Take care :)

**Comment by mirasrael** [comment]
Hi @bogdanRada. I also thought about almost same things and I agree what it is good to have some trial period. So lets go this way. I will add you to collaborators.

**Comment by bogdanRada** [comment]
Thank you very much

**Comment by bogdanRada** [comment]
Hello. As i pointed out în pull request #32 i will.be unable to help maintaining this project. I am sorry for this.

I think also this should be closed în favor of issue #33 where there îs a discussion about maintainers.

I wish everyone good luck with this project.
