### ISSUE TITLE
it's not working with activeadmin

### ISSUE THREAD

**Issue by rainchen** [mirasrael/daemons-rails#6]
when runs the ./lib/daemons/mail_ctl start
it will raise something like
app/admin/admin_user.rb:3:in `<top (required)>': uninitialized constant AdminUser (NameError)

**Comment by BenZhang** [comment]
Thank you very much @mirasrael. I was experiencing exact the same problem. 
Adding Dir.chdir(root) before the require File.dirname(__FILE__) + "/../../config/environment"
Fix the ActiveAdmin problem.
